### PR TITLE
No camera static image

### PR DESCRIPTION
**Pull request by link00000000**
# Relies on #42 

## Notable Changes

-   assets/no_camera.bmp is display at startup
-   Static image is replaced with video feed when device connects
-   assets/no_camera.bmp is displayed again after a connection is terminated

## Changelog

-   Add no camera image assets
-   Move mimic_logo.ico to assets/favicon.ico
-   merged in branch 'camera-rotation'
-   Show static frames when no device is initially connected
-   Show static image after video connection is lost

### CODE REVIEW

**Comment by link00000000** [comment]
Assets were moved in this branch so build scripts and paths need updated before merge

**Comment by link00000000** [comment]
Just a note for myself so that it didn't get merged before that was fixed.

**Comment by link00000000** [comment]
Just gonna have you take one more look at the last few changes I made just in case before merging.

**Review by UnknwonWarlock — APPROVED** [review]
Nice work!

**Pull request merged**
